### ISSUE TITLE
Externalizing JWKs as kubernetes environment variable fails

### ISSUE THREAD

**Issue by codingkapoor** [pac4j/lagom-pac4j#33]
As long as you use jwk in `application.con` things turn out just fine.
```
pac4j.lagom.jwt.authenticator {
  signatures = [
    {
      algorithm = "RS256"
      jwk = {"kty":"RSA","e":"AQAB","n":"ghhDZxuUo6TaSvAlD23mLP6n_T9pQuJsFY4JWdBYTjtcp_8Q3QeR477jou4cScPGczWw2JMGnx-Ao_b7ewagSl7VHpECBFHgcnlAgs5j6jfnd3M9ADKD2Yc756iXlIMT9xKDblIcXQQYlXalqxGvnLRLv1KAgVVVpVWzQd6Iz8WdTnexVrh7L9N87QQbOWcAVWGHCWCLCBsVE7JbC-XDt9h9P1g1sMqMV-qp7HjSXUKWuF2NwOnL2VeFSED7gdefs2Za1UYqhfwxdGl7aaPDXhjib0cfg4NvbcXMzxDEVkeJqhdDfD82wHOs4qFvnFMVxq9n6VVExSxsJq8gBJ7Z2AmfoXpmZC1L1ZwULB2KKpFXDCzgBELPLrfyIf8mNnk2nuuLT-aaMsqy2uB-ea3du4lyWo9MLk6x-L5g-n1oADKFKBY9aP2QQwruCG92XSd7jA9yLtbgr9OGVCYezxIxFp4vW6KcmPwJQjozWtwkZjeo4hv-zhRac73WDox2hDkif7WPTuEvC21fRy3GvyPIUPKPJA8pJjb2TXT7DXknR97CTnOWicuh3HMoRlVIwUzM5SVLGSXex0VjHZKgLYwQYukg5O2rab_4NxpD6LqLHx1bbPssC7BedCIfWX1Vcae40tlfvJAM09MiwQPZjWRahW_fK_9X5F5_rtUhCznm32M"}
    },
    {
      algorithm = "RS256"
      jwk = {"kty":"RSA","e":"AQAB","n":"u0TRU7AzGnh_hIIOLQwV_pi27xvoMVrIQr42wJsVyVRJeovUYT7hWmN-8LLieTbZ1uNJO88WqFkByP6uadU2oTEBh7TLwH4eKOyFERzURozc3gWyjhPfDWCQYBcYlC18L2bQul1kTzMVvfmCpIWyhSqDmlv4uLXZGJK0iF0Dzukn7ewAAM0qFrDq6GhYbsf2yo2Gq0tMLhPCwvn8BgjVuoRwq454B3GDyZXwGndRlr0o502otVzKRsd7I7Xvk0jgz9Nuu2S5dgsDgUCcKnUrWnitRwNKpnkfBYdY5ZU5O9YTmM20jVu0W6l63o2iibaAMGSkqzN3-i_v7LLMXkvWYpFoOtTE6s3s1x8sikK5DQ3uAzShC65iSj3YGbgjZ5fNU4wT1NS-QkGiMUz2O7Lt3rX9LrnF85CZP2HnX24v4pZNxklWxCvM2CUdvGKav1gIz_cqbgj8wsPAUohE2nDvHWXD6x7WoJJPDm3z03qEFXUVyZLnhJ7YPSv6WS5QyDYLUXs-nD3QEsFjVDlCBOxL4SvUTanfckljhEvIxy7XcSIh7oWy6_6CSGnNvHr572rUVWBaSVtYLarbueKwpAwwWy1YB7JZElc0HT6v7fmuREENBjJWO0MSQe_lRn_0JlCcYXEdg0dy8ozYyywQAAM6IPvEn2OiSnIH06ftd5Fz-48"}
    }
  ]
}
```

But when I try to externalize the same for production purposes as kubernetes environment variable, loading jwk falls flat!

```
Config(SimpleConfigObject({"signatures":["{\n  algorithm = \"RS256\"\n  jwk = {\"kty\":\"RSA\",\"e\":\"AQAB\",\"n\":\"ghhDZxuUo6TaSvAlD23mLP6n_T9pQuJsFY4JWdBYTjtcp_8Q3QeR477jou4cScPGczWw2JMGnx-Ao_b7ewagSl7VHpECBFHgcnlAgs5j6jfnd3M9ADKD2Yc756iXlIMT9xKDblIcXQQYlXalqxGvnLRLv1KAgVVVpVWzQd6Iz8WdTnexVrh7L9N87QQbOWcAVWGHCWCLCBsVE7JbC-XDt9h9P1g1sMqMV-qp7HjSXUKWuF2NwOnL2VeFSED7gdefs2Za1UYqhfwxdGl7aaPDXhjib0cfg4NvbcXMzxDEVkeJqhdDfD82wHOs4qFvnFMVxq9n6VVExSxsJq8gBJ7Z2AmfoXpmZC1L1ZwULB2KKpFXDCzgBELPLrfyIf8mNnk2nuuLT-aaMsqy2uB-ea3du4lyWo9MLk6x-L5g-n1oADKFKBY9aP2QQwruCG92XSd7jA9yLtbgr9OGVCYezxIxFp4vW6KcmPwJQjozWtwkZjeo4hv-zhRac73WDox2hDkif7WPTuEvC21fRy3GvyPIUPKPJA8pJjb2TXT7DXknR97CTnOWicuh3HMoRlVIwUzM5SVLGSXex0VjHZKgLYwQYukg5O2rab_4NxpD6LqLHx1bbPssC7BedCIfWX1Vcae40tlfvJAM09MiwQPZjWRahW_fK_9X5F5_rtUhCznm32M\"}\n}\n","{\n  algorithm = \"RS256\"\n  jwk = {\"kty\":\"RSA\",\"e\":\"AQAB\",\"n\":\"u0TRU7AzGnh_hIIOLQwV_pi27xvoMVrIQr42wJsVyVRJeovUYT7hWmN-8LLieTbZ1uNJO88WqFkByP6uadU2oTEBh7TLwH4eKOyFERzURozc3gWyjhPfDWCQYBcYlC18L2bQul1kTzMVvfmCpIWyhSqDmlv4uLXZGJK0iF0Dzukn7ewAAM0qFrDq6GhYbsf2yo2Gq0tMLhPCwvn8BgjVuoRwq454B3GDyZXwGndRlr0o502otVzKRsd7I7Xvk0jgz9Nuu2S5dgsDgUCcKnUrWnitRwNKpnkfBYdY5ZU5O9YTmM20jVu0W6l63o2iibaAMGSkqzN3-i_v7LLMXkvWYpFoOtTE6s3s1x8sikK5DQ3uAzShC65iSj3YGbgjZ5fNU4wT1NS-QkGiMUz2O7Lt3rX9LrnF85CZP2HnX24v4pZNxklWxCvM2CUdvGKav1gIz_cqbgj8wsPAUohE2nDvHWXD6x7WoJJPDm3z03qEFXUVyZLnhJ7YPSv6WS5QyDYLUXs-nD3QEsFjVDlCBOxL4SvUTanfckljhEvIxy7XcSIh7oWy6_6CSGnNvHr572rUVWBaSVtYLarbueKwpAwwWy1YB7JZElc0HT6v7fmuREENBjJWO0MSQe_lRn_0JlCcYXEdg0dy8ozYyywQAAM6IPvEn2OiSnIH06ftd5Fz-48\"}\n}\n"]}))
Oops, cannot start the server.
com.typesafe.config.ConfigException$WrongType: env variables: signatures has type list of STRING rather than list of OBJECT
	at com.typesafe.config.impl.SimpleConfig.getHomogeneousWrappedList(SimpleConfig.java:452)
	at com.typesafe.config.impl.SimpleConfig.getObjectList(SimpleConfig.java:460)
	at com.typesafe.config.impl.SimpleConfig.getConfigList(SimpleConfig.java:465)
	at org.pac4j.lagom.jwt.JwtAuthenticatorHelper.parse(JwtAuthenticatorHelper.java:84)
```

I understand that environment variables has to be string and `pac4j.lagom.jwt.authenticator` value has to be a json object but what could be an alternate way to provision jwk in production environments? If we don't externalize jwks as kubernetes environment or secret, we will end up building and redeploying the app everytime we need to update the jwk!  

P.S. I have explained the externization steps in [this](https://stackoverflow.com/questions/62059150/how-to-create-kubernetes-secret-as-json-object-and-load-the-same-in-kubernetes-e) stackoverflow post.

Please suggest.

**Comment by ihostage** [comment]
Hello @codingkapoor! 👋 
We use K8S for production environments too. But we [map a K8S Secret to file](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) instead env variable 😄 
1. Create a K8S Secret with `pac4j.lagom.jwt.authenticator` configuration.
2. Map Secret to file (for example `/opt/conf/auth.conf`) in pod
3. Add include to your `application.conf`
```HOCON
include file("/opt/conf/auth.conf")
```
4. Profit! 😉

**Comment by ihostage** [comment]
Moreover, we use the same approach with K8S `ConfigMap`. And now we can change **any** HOCON configuration (Akka/Play/Lagom or custom) for **any** K8S environments (test, staging, production). Very useful 😉 

PS: `logback.xml` also mapped from `ConfigMap` 😂  For flexibility configuration of logger on different environments.

**Comment by codingkapoor** [comment]
And what would `application.conf` look like? Replacing the following with?
```
pac4j.lagom.jwt.authenticator {
  signatures = [
    {
      algorithm = "RS256"
      jwk = {"kty":"RSA","e":"AQAB","n":"ghhDZxuUo6TaSvAlD23mLP6n_T9pQuJsFY4JWdBYTjtcp_8Q3QeR477jou4cScPGczWw2JMGnx-Ao_b7ewagSl7VHpECBFHgcnlAgs5j6jfnd3M9ADKD2Yc756iXlIMT9xKDblIcXQQYlXalqxGvnLRLv1KAgVVVpVWzQd6Iz8WdTnexVrh7L9N87QQbOWcAVWGHCWCLCBsVE7JbC-XDt9h9P1g1sMqMV-qp7HjSXUKWuF2NwOnL2VeFSED7gdefs2Za1UYqhfwxdGl7aaPDXhjib0cfg4NvbcXMzxDEVkeJqhdDfD82wHOs4qFvnFMVxq9n6VVExSxsJq8gBJ7Z2AmfoXpmZC1L1ZwULB2KKpFXDCzgBELPLrfyIf8mNnk2nuuLT-aaMsqy2uB-ea3du4lyWo9MLk6x-L5g-n1oADKFKBY9aP2QQwruCG92XSd7jA9yLtbgr9OGVCYezxIxFp4vW6KcmPwJQjozWtwkZjeo4hv-zhRac73WDox2hDkif7WPTuEvC21fRy3GvyPIUPKPJA8pJjb2TXT7DXknR97CTnOWicuh3HMoRlVIwUzM5SVLGSXex0VjHZKgLYwQYukg5O2rab_4NxpD6LqLHx1bbPssC7BedCIfWX1Vcae40tlfvJAM09MiwQPZjWRahW_fK_9X5F5_rtUhCznm32M"}
    },
    {
      algorithm = "RS256"
      jwk = {"kty":"RSA","e":"AQAB","n":"u0TRU7AzGnh_hIIOLQwV_pi27xvoMVrIQr42wJsVyVRJeovUYT7hWmN-8LLieTbZ1uNJO88WqFkByP6uadU2oTEBh7TLwH4eKOyFERzURozc3gWyjhPfDWCQYBcYlC18L2bQul1kTzMVvfmCpIWyhSqDmlv4uLXZGJK0iF0Dzukn7ewAAM0qFrDq6GhYbsf2yo2Gq0tMLhPCwvn8BgjVuoRwq454B3GDyZXwGndRlr0o502otVzKRsd7I7Xvk0jgz9Nuu2S5dgsDgUCcKnUrWnitRwNKpnkfBYdY5ZU5O9YTmM20jVu0W6l63o2iibaAMGSkqzN3-i_v7LLMXkvWYpFoOtTE6s3s1x8sikK5DQ3uAzShC65iSj3YGbgjZ5fNU4wT1NS-QkGiMUz2O7Lt3rX9LrnF85CZP2HnX24v4pZNxklWxCvM2CUdvGKav1gIz_cqbgj8wsPAUohE2nDvHWXD6x7WoJJPDm3z03qEFXUVyZLnhJ7YPSv6WS5QyDYLUXs-nD3QEsFjVDlCBOxL4SvUTanfckljhEvIxy7XcSIh7oWy6_6CSGnNvHr572rUVWBaSVtYLarbueKwpAwwWy1YB7JZElc0HT6v7fmuREENBjJWO0MSQe_lRn_0JlCcYXEdg0dy8ozYyywQAAM6IPvEn2OiSnIH06ftd5Fz-48"}
    }
  ]
}
```

**Comment by ihostage** [comment]
You can keep this configuration with default values, for example. Just add `include` after this block. But more useful, if you add `include` to end of the file.

```HOCON
akka {
   ... configuration for Akka ...
}
play {
   ... configuration for Play ...
}
lagom {
   ... configuration for Lagom ...
}
pac4j {
  ... configuration for Pac4j ...
  lagom.jwt.authenticator {
  signatures = [ ... ]
}

...

include file("/opt/conf/secret.conf")
```

**Comment by ihostage** [comment]
ConfigMap (or Secrets)
```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-service-config
data:
  conf: |
    pac4j {
      lagom.jwt.authenticator {
        signatures = [ ... ]
      }
    }
```

Deployment
```YAML
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: my-service
  labels:
    app: my-service
spec:
  ...
  template:
    ...
    spec:
      containers:
        - name: my-service
          ...
          volumeMounts:
            - name: "my-service-config-volume"
              mountPath: "/opt/conf"
      volumes:
        - name: "my-service-config-volume"
          configMap:
            name: "my-service-config"
            items:
              - key: conf
                path: "config.conf"

```

**Comment by codingkapoor** [comment]
@ihostage It worked seemlessly! Thanks for your help.

**Comment by ihostage** [comment]
You are welcome!
